export const SETUP_APP = "SETUP_APP";
export const ATTEMPT_REGISTRATION = "ATTEMPT_REGISTRATION";

export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";
export const LOG_OUT = "LOG_OUT";

export const ATTEMPT_SEND_EMAIL = "ATTEMPT_SEND_EMAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const SAVE_COURSES = "SAVE_COURSES";

export const GET_CURRICULUM = "GET_CURRICULUM";
export const SAVE_CURRICULUM = "SAVE_CURRICULUM";
export const SET_CURRICULUM = "SET_CURRICULUM";

export const ADD_REG_CODE = "ADD_REG_CODE";

export const GET_ALL_GRADES = "GET_ALL_GRADES";
export const SAVE_GRADES = "SAVE_GRADES";