export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const ATTEMPT_REGISTRATION = "ATTEMPT_REGISTRATION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";