export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const ATTEMPT_REGISTRATION = "ATTEMPT_REGISTRATION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";
export const ATTEMPT_SEND_EMAIL = "ATTEMPT_SEND_EMAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";